name: Android Build Release

on: pull_request

jobs:
  build:
#    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app\build\outputs\apk\prodFlavor\release
          signingKeyBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}
          alias: ${{ secrets.GOOGLE_PLAY_ALIAS }}
          keyStorePassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
          keyPassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt