name: Android Production Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  test_and_build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set version code
      run: |
        echo VERSION_CODE=`expr $GITHUB_RUN_NUMBER + 103` >> $GITHUB_ENV

    - name: Run Tests
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Release AAB
      run: ./gradlew bundleRelease

    - uses: actions/upload-artifact@v3
      with:
        name: app-build-outputs
        path: app/build/outputs/

  deploy_google_play:

    runs-on: ubuntu-20.04
    needs: [test_and_build]

    steps:

    - uses: actions/download-artifact@v3
      with:
        name: app-build-outputs
        path: app/build/outputs/

    - name: Sign AAB  
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}
        alias: ${{ secrets.GOOGLE_PLAY_ALIAS }}
        keyStorePassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
        keyPassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
        
    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{secrets.GOOGLE_PLAY_PUBLISHING_ACCOUNT}}
        packageName: com.bupp.wood_spoon_eaters
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: alpha
