name: Android Production Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set version code
      run: export VERSION_CODE=`expr $GITHUB_RUN_NUMBER + 103`; echo Next versionCode is $VERSION_CODE

    - name: Run Tests
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Release AAB
      run: ./gradlew bundleRelease
      
    - name: Sign AAB  
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}
        alias: ${{ secrets.GOOGLE_PLAY_ALIAS }}
        keyStorePassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
        keyPassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
        
    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{secrets.GOOGLE_PLAY_PUBLISHING_ACCOUNT}}
        packageName: com.bupp.wood_spoon_eaters
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: alpha
