name: Android Production Release

on:
  push:
    branches:
      - develop
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set version code
      run: |
        echo VERSION_CODE=`expr $GITHUB_RUN_NUMBER + 103` >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew clean
      
    - name: Build with Gradle
      run: ./gradlew --stop

    - name: Build with Gradle
      run: ./gradlew apps:eaters:assembleRelease --no-daemon -x lint --stacktrace --debug --info

    - name: Build Release AAB
      run: ./gradlew bundleRelease

    - name: Eaters – Publish To App Center
      if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release')
      uses: wzieba/AppCenter-Github-Action@v1.3.2
      with:
        appName: Monkeytech/WoodSpoon-Android
        token: ${{ secrets.APP_CENTER_TOKEN }}
        group: WoodSpoon Android Testers
        file: apps/eaters/build/outputs/apk/staging/debug/eaters-staging-debug.apk
        releaseNotes: "Staging version.\nBuild number ${{env.VERSION_CODE}}\n ${{ github.event.head_commit.message }}"
        notifyTesters: false
        debug: true

    - name: Cooks – Publish To App Center
      if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release')
      uses: wzieba/AppCenter-Github-Action@v1.3.2
      with:
        appName: Monkeytech/WoodSpoon-Chef-Android
        token: ${{ secrets.APP_CENTER_TOKEN }}
        group: WoodSpoon Android Testers
        file: apps/cooks/build/outputs/apk/staging/debug/cooks-staging-debug.apk
        releaseNotes: "Staging version.\nBuild number ${{env.VERSION_CODE}}\n ${{ github.event.head_commit.message }}"
        notifyTesters: false
        debug: true

    - name: Extracting Release App Name
      if: startsWith(github.ref, 'refs/heads/release')
      run: echo "$(echo "RELEASE_APP_NAME=")$(echo ${{github.ref}} | cut -d/ -f4)" >> $GITHUB_ENV

    - name: Printing Release App Name
      if: env.RELEASE_APP_NAME != ''
      run: echo "Releasing app named [$RELEASE_APP_NAME]"

    - name: Eaters – Sign AAB
      if: env.RELEASE_APP_NAME == 'eaters'
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: apps/eaters/build/outputs/bundle/productionRelease
        signingKeyBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}
        alias: ${{ secrets.GOOGLE_PLAY_ALIAS }}
        keyStorePassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
        keyPassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}

    - name: Eaters – Deploy to Play Store
      if: env.RELEASE_APP_NAME == 'eaters'
      uses: r0adkll/upload-google-play@v1.0.18
      with:
        serviceAccountJsonPlainText: ${{secrets.GOOGLE_PLAY_PUBLISHING_ACCOUNT}}
        packageName: com.bupp.wood_spoon_eaters
        releaseFiles: apps/eaters/build/outputs/bundle/productionRelease/eaters-production-release.aab
        track: internal
        changesNotSentForReview: true

    - name: Cooks – Sign AAB
      if: env.RELEASE_APP_NAME == 'cooks'
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: apps/cooks/build/outputs/bundle/productionRelease
        signingKeyBase64: ${{ secrets.COOKS_GOOGLE_PLAY_SIGNING_KEY }}
        alias: ${{ secrets.COOKS_GOOGLE_PLAY_ALIAS }}
        keyStorePassword: ${{ secrets.COOKS_GOOGLE_PLAY_PASSWORD }}
        keyPassword: ${{ secrets.cooks.GOOGLE_PLAY_PASSWORD }}

    - name: Cooks – Deploy to Play Store
      if: env.RELEASE_APP_NAME == 'cooks'
      uses: r0adkll/upload-google-play@v1.0.18
      with:
        serviceAccountJsonPlainText: ${{secrets.GOOGLE_PLAY_PUBLISHING_ACCOUNT}}
        packageName: com.bupp.wood_spoon_chef
        releaseFiles: apps/cooks/build/outputs/bundle/productionRelease/cooks-production-release.aab
        track: internal
        changesNotSentForReview: true
