on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: send to qa (staging)
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Building staging version
      run: ./gradlew assembleRelease

    - name: Publish To App Center
      uses: wzieba/AppCenter-Github-Action@v1.3.2
      with:
        appName: WoodSpoon-Android
        token: ${{ secrets.APP_CENTER_TOKEN }}
        group: WoodSpoon Android Testers
        file:  app/build/outputs/apk/prodFlavor/release/app-prodFlavor-release-unsigned.apk
        notifyTesters: true
        debug: true