on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'prod-v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: send to qa (prod)
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Building production version
        run: ./gradlew assembleRelease

      - name: Publish To App Center
        uses: wzieba/AppCenter-Github-Action@v1.3.2
        with:
          appName: Monkeytech/WoodSpoon-Android
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: WoodSpoon Android Testers
          file:  app/build/outputs/apk/prodFlavor/release/app-prodFlavor-release-unsigned.apk
          releaseNotes: 'Production version'
          notifyTesters: true
          debug: true

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: androidRulez
          SLACK_TITLE: 'New version is out! - PRODUCTION'
          SLACK_MESSAGE: 'Check out this new version'