on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: send to qa (staging)
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Building staging version
      run: ./gradlew assembleRelease

#    - name: Sign APK
#        uses: r0adkll/sign-android-release@v1
#        # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: app/build/outputs/apk/prodFlavor/release/
#          signingKeyBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}
#          alias: ${{ secrets.GOOGLE_PLAY_ALIAS }}
#          keyStorePassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
#          keyPassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}

    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.3.2
      with:
        appName: Monkeytech/WoodSpoon_Eaters
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: WoodsPoons
        file:  app/build/outputs/apk/prodFlavor/release/app-prodFlavor-release-unsigned.apk
        notifyTesters: true
        debug: true